Aimbot Implementation
mayfairr/mango pull request #5
Opened 2020-12-14 14:54 UTC by mayfairr

Aimbot is unresolved for all values of tanx in the range  x<-pi and x>pi. This can be fixed by instantiating a clamping algorithm of some kind.

2020-12-14 15:24 UTC, star-1337 requested changes
Very good! need to move entity list back into main so it can be used by other functions.
When converting entity's positions into a 2D vector please make it a function show it can be used by other functions.

2020-12-15 09:47 UTC, mayfairr commented
@star-1337 Don't think I can move entity loop into _main.cpp_ since it will iterate each entity asynchronously causing it to become out of sync. I can maybe create an iterative loop which calls a method on each entity but this solution will only work on entities that are independent and need to be called on their own. I.e. works for glow but will not work for some other features? Should I still implement this?

2020-12-15 13:27 UTC, star-1337 commented
Don't implement.

2020-12-16 14:59 UTC, star-1337 approved these changes

2020-12-16 15:03 UTC, merged